checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints/
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
data_stages:
- data:
    dataset:
      training_folder: datasets/c4-es/train
      validation_folder: datasets/c4-es/validation
      lang_to_ids:
        es: 128002
    num_loading_workers: 1
    seed: 42
  name: General purpose training (Single dataset)
  start_training_step: 1
- data:
    dataset:
      training_folder:
      - datasets/c4-es/train
      - datasets/c4-en/train
      - datasets/c4-fr/train
      validation_folder:
      - datasets/c4-es/validation
      - datasets/c4-en/validation
      - datasets/c4-fr/validation
      lang_to_ids:
        es: 128002
        en: 128003
        fr: 128004
    num_loading_workers: 1
    seed: 42
  name: Second purpose training (> 1 dataset)
  start_training_step: 15
- data:
    dataset:
      training_folder:
        datasets/c4-es/train: 0.6
        datasets/c4-en/train: 0.3
        datasets/c4-fr/train: 0.1
      validation_folder:
      - datasets/c4-es/validation
      - datasets/c4-en/validation
      - datasets/c4-fr/validation
      lang_to_ids:
        es: 128002
        en: 128003
        fr: 128004

    num_loading_workers: 1
    seed: 42
  name: Third purpose training (Blended dataset)
  start_training_step: 25
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: Nanoset
  run: llama
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 512
    initializer_range: 0.02
    intermediate_size: 512
    is_llama_config: true
    max_position_embeddings: 1024
    num_hidden_layers: 2
    num_attention_heads: 32
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rope_interleaved: false
    rope_theta: 500000.0
    rms_norm_eps: 1.0e-06
    rope_scaling: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 98
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: REDUCE_SCATTER
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: meta-llama/Meta-Llama-3-8B
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 10
  micro_batch_size: 4
  sequence_length: 1024
  train_steps: 200
  val_check_interval: -1
