checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints/xglm
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 64
      hf_dataset_config_name: null
      hf_dataset_or_datasets: DKYoon/SlimPajama-6B
      hf_dataset_splits: train
      text_column_name: text
    num_loading_workers: 1
    seed: 42
  name: Finetuning
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: xglm-test
  run: xglm-dp4tp1pp1
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    path: /capstor/scratch/cscs/ahernnde/checkpoints/xglm-564M
  make_vocab_size_divisible_by: 1
  model_config:
    activation_function: gelu
    attn_pdrop: 0.1
    embd_pdrop: 0.1
    scale_embedding: true
    eos_token_id: 2
    hidden_size: 1024
    intermediate_size: 4096
    layer_norm_epsilon: 0.00001
    max_position_embeddings: 2048
    num_attention_heads: 16
    num_hidden_layers: 24
    resid_pdrop: 0.1
    scale_attention_softmax_in_fp32: true
    scale_attn_weights: true
    vocab_size: 256008
    sinusoidal_position_embedding: true
    position_embedding_offset: 2
    use_spda: false
    act_pdrop: 0.0
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 900
    lr_decay_style: cosine
    lr_warmup_steps: 100
    lr_warmup_style: linear
    min_decay_lr: 1.0e-04
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: REDUCE_SCATTER
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: facebook/xglm-564M
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 4
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 8
  sequence_length: 2048
  train_steps: 1000
  val_check_interval: -1
